# Generated by Django 4.0.2 on 2022-02-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_taskassign',
            old_name='files',
            new_name='projectfiles',
        ),
    ]
