# Generated by Django 4.0.2 on 2022-02-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_files_project_taskassign_projectfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leave',
            new_name='applyleave',
        ),
    ]
