# Generated by Django 4.0.2 on 2022-03-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_project_taskassign_extension_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tester',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projecttester', to='base_app.user_registration'),
        ),
    ]
