# Generated by Django 4.0.2 on 2022-03-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_test_status_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='branch',
        ),
    ]
