# Generated by Django 4.0.2 on 2022-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_rename_files_project_projectfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rejectdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
